In [6]:
import numpy as np
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier

# Load dataset
data = load_wine()
X, y = data.data, data.target

# Normalize data to [-1, 1]
scaler = MinMaxScaler(feature_range=(-1, 1))
X_scaled = scaler.fit_transform(X)

# Split data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, train_size=0.8, random_state=42)

# Define the MLP model
mlp = MLPClassifier(hidden_layer_sizes=(3, 3), max_iter=1000, random_state=42)

# Train the model
mlp.fit(X_train, y_train)

# Evaluate the model
print(f"Training accuracy: {mlp.score(X_train, y_train):.4f}")
print(f"Testing accuracy: {mlp.score(X_test, y_test):.4f}")

# Display the weights of each layer
for i, weights in enumerate(mlp.coefs_):
    print(f"Weights of layer {i}:")
    print(weights)


Training accuracy: 0.9718
Testing accuracy: 1.0000
Weights of layer 0:
[[-0.02398047 -0.06142474  1.60383381]
 [ 0.24807071 -1.16281608 -0.38348136]
 [-0.37751181  0.24781204  1.22766895]
 [ 0.21670224 -0.29125484 -0.36921443]
 [ 0.40827064 -0.79585435 -0.44526018]
 [-0.30962877  0.43376605  0.32698475]
 [ 0.06194486  0.56139475 -0.18042594]
 [-0.25915055 -0.51965966 -0.48614533]
 [-0.08572172 -0.21349631 -0.2789322 ]
 [ 0.15688433 -0.60941676  0.0643632 ]
 [ 0.11954247  0.43114669 -1.39825604]
 [ 0.41462639  1.16455626  0.31647097]
 [-0.1296037  -0.91388476  1.11817309]]
Weights of layer 1:
[[-0.77084611  0.75298096 -0.59398787]
 [ 1.16423987 -0.84044597 -0.32983806]
 [-0.17153465 -0.06660914  1.53212548]]
Weights of layer 2:
[[ 0.63224778  1.50136338 -1.41062637]
 [-1.62713447 -0.53405628  0.37100888]
 [ 0.56166365 -1.04930851  0.72990315]]


C:\Users\Rober\miniconda3\envs\tf\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
